### ISSUE TITLE
Staging Genesis configuration breaks

### ISSUE THREAD

**Issue by flipchan** [liberland/liberland_substrate#106]
Tracelog: 
```
./liberland_run build-spec --chain=liberland.json --raw > fluff.json
2022-09-24 17:25:25 Building chain spec    
2022-09-24 17:25:28 [0] 💸 generated 3 npos voters, 3 from validators and 0 nominators    

====================

Version: 3.0.0-dev-ceb4c6e4a-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:586:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   6: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   7: <pallet_elections_phragmen::pallet::GenesisConfig<T> as frame_support::traits::hooks::GenesisBuild<T>>::build
   8: std::thread::local::LocalKey<T>::with
   9: sp_state_machine::basic::BasicExternalities::execute_with_storage
  10: <node_runtime::GenesisConfig as sp_runtime::BuildStorage>::assimilate_storage
  11: sp_runtime::BuildStorage::build_storage
  12: <sc_chain_spec::chain_spec::ChainSpec<G,E> as sc_chain_spec::ChainSpec>::as_json
  13: sc_service::chain_ops::import_blocks::build_spec
  14: sc_cli::commands::build_spec_cmd::BuildSpecCmd::run
  15: sc_cli::runner::Runner<C>::sync_run
  16: node_cli::command::run
  17: substrate::main
  18: std::sys_common::backtrace::__rust_begin_short_backtrace
  19: std::rt::lang_start::{{closure}}
  20: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:48
      std::panicking::try::do_call
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:20
  21: main
  22: __libc_start_main
  23: _start


Thread 'main' panicked at 'Genesis member does not have enough stake.',frame/elections-phragmen/src/lib.rs:708

This is a bug. Please report it at:

	https://github.com/paritytech/substrate/issues/new

```

**Comment by flipchan** [comment]
validator updates:
```
./substrate --chain fluff       --validator --in-peers 256 --base-path /home/filip/liberland_chain/ \
--bootnodes /ip4/162.55.230.227/tcp/30333/p2p/12D3KooWBPQ8H9KHi5axKmRerR289nxTeBPASQAwScjHTircdioF \

        --name validator_name_here  \
                        --node-key node-key-file \                                                   
                                        --telemetry-url "ws://telemetry.laissez-faire.trade:8001/submit 1"
```

**Comment by flipchan** [comment]
fixed

**Comment by flipchan** [comment]
remove election members in chainspec to solve
